# Generated by Django 2.2.5 on 2019-11-11 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('rating', models.FloatField()),
                ('genre', models.TextField()),
                ('runtime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime', models.DateTimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('purchased_at', models.DateField()),
                ('showing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Showing')),
            ],
        ),
    ]
